import { GraphQLClient, gql } from "graphql-request";
import { NextPage } from "next";
import Head from "next/head";
import { motion, useAnimation } from "framer-motion";
import styles from "../../styles/Authors.module.css";
import Link from "next/link";

//Graphcms
const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl4m6kpla7bry01xv5pop3nrl/master"
);

const QUERY = gql`
  {
    authors {
      name
      position
      avatar {
        url
      }
    }
  }
`;

export const getStaticProps = async () => {
  const { authors } = await graphcms.request(QUERY);
  return {
    props: { authors },
    revalidate: 10,
  };
};

export const Authors: NextPage = (authors: any) => {
  // Framer-motion
  const ToggleSocialMediaAccounts = useAnimation();

  const SocialMediaAccountsVariants = {
    hidden: {
      height: "0%",
    },
    display: {
      height: "max-content",
    },
  };

  return (
    <div>
      <Head>
        <title>Workoutly Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.container}>
          <Link href="/">
            <span className={styles.backButton}>
              <i className="fa-solid fa-circle-chevron-left"></i>
            </span>
          </Link>

          <div className={styles.header}>
            <h1>Meet our authors</h1>
            <p>The most educational and talented individuals</p>
          </div>
          <div className={styles.authorsContainer}>
            {authors.authors.map((author: any) => (
              <div
                key={Math.random() * 1000}
                className={styles.authorsInfoContainer}
                onMouseOver={() => ToggleSocialMediaAccounts.start("display")}
                onMouseLeave={() => ToggleSocialMediaAccounts.start("hidden")}
              >
                <div className={styles.avatarContainer}>
                  <img src={author.avatar.url} alt="" />
                </div>
                <div className={styles.authorInfo}>
                  <p className={styles.name}>{author.name}</p>
                  <p className={styles.position}>{author.position}</p>
                </div>
                <div className={styles.socialMediaAccounts}>
                  <i className="fa-brands fa-facebook"></i>
                  <i className="fa-brands fa-twitter"></i>
                  <i className="fa-brands fa-instagram"></i>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
};

export default Authors;
